#include<stdio.h>
main()
{
    int n;
    scanf("%d",&n);
    int i,j,k;
    int x=0;
    if(n%2==0)
    {
        for(i=0;i<n/2;i++)
        {
            x=0;
            for(j=(n/2)-1;j>i;j--)
            {
                x++;
                printf("-");
            }
            printf("*");
            x++;
            while(x<(n/2)+i-1)
            {
                printf("-");
                x++;
            }
            if(i!=0)
            {
                printf("*");
                x++;
            }
            while(x<n-1)
            {
                printf("-");
                x++;
            }
            printf("\n");
        }
        for(i=0;i<n/2;i++)
        {
            x=0;
            for(j=0;j<i;j++)
            {
                printf("-");
                x++;
            }
            printf("*");
            x++;
            while(x<n-i-2)
            {
                printf("-");
                x++;
            }
            if(i!=(n/2)-1)
            {
                printf("*");
                x++;
            }
            while(x<n-1)
            {
                printf("-");
                x++;
            }
            printf("\n");
        }
    }
    else
    {
        for(i=0;i<n/2;i++)
        {
            x=0;
            for(j=i;j<(n/2);j++)
            {
                printf("-");
                x++;
            }
            printf("*");
            x++;
            while(x<(n/2)+i)
            {
                printf("-");
                x++;
            }
            if(i!=0)
            {
                printf("*");
                x++;
            }
            while(x!=n)
            {
                printf("-");
                x++;
            }
            printf("\n");
        }
        for(i=0;i<=n/2;i++)
        {
            x=0;
            for(j=0;j<i;j++)
            {
                printf("-");
                x++;
            }
            printf("*");
            x++;
            while(x<n-i-1)
            {
                printf("-");
                x++;
            }
            if(i!=n/2)
            {
                printf("*");
                x++;
            }
            while(x!=n)
            {
                printf("-");
                x++;
            }
            printf("\n");
        }
    }
}
